branch-defaults:
  master:
    environment: AntiFeedServer-dev
    group_suffix: null
global:
  application_name: AntiFeedServer
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
